# Generated by Django 5.1.2 on 2024-10-16 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_tg', models.CharField(blank=True, max_length=150, null=True, verbose_name='Юсер пользователя')),
                ('name_tg', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя пользователя')),
                ('phone_tg', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('tg_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID Телеграм')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Статус администратора')),
                ('language', models.CharField(default='ru', max_length=10, verbose_name='Язык интерфейса')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='GroupsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Название курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_post', models.TextField(blank=True, null=True, verbose_name='Описание для поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proweb_bot.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100, unique=True, verbose_name='ID группы')),
                ('name_group', models.CharField(max_length=200, verbose_name='Название группы')),
                ('language', models.CharField(blank=True, max_length=5, null=True, verbose_name='Язык группы')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proweb_bot.groupscategory', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='MediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post_media/photo/', verbose_name='Фото поста')),
                ('video', models.FileField(blank=True, null=True, upload_to='post_media/video/', verbose_name='Видео')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proweb_bot.posts', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Медиа для поста',
                'verbose_name_plural': 'Медиа для постов',
            },
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, verbose_name='ID сообщения в группе')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proweb_bot.groups', verbose_name='Группа')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proweb_bot.posts', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Пост-Группа',
                'verbose_name_plural': 'Посты в Группах',
            },
        ),
    ]
