# Generated by Django 5.1.2 on 2024-10-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proweb_bot', '0002_posts_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='post_media/voices/'),
        ),
    ]
