# Generated by Django 5.1.2 on 2024-10-16 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proweb_bot', '0003_mediapost_voice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppost',
            options={'verbose_name': 'Пост в группе', 'verbose_name_plural': 'Посты в Группах'},
        ),
        migrations.AddField(
            model_name='posts',
            name='media',
            field=models.JSONField(default=list, verbose_name='Список медиа'),
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='proweb_bot.customuser', verbose_name='Пользователи'),
        ),
        migrations.CreateModel(
            name='UserGroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255, verbose_name='ID чата')),
                ('message_id', models.CharField(max_length=255, verbose_name='ID сообщения')),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proweb_bot.posts', verbose_name='Пост для пользователя')),
            ],
            options={
                'verbose_name': 'Пост в чате',
                'verbose_name_plural': 'Посты в чатах',
            },
        ),
    ]
