# Generated by Django 5.1.2 on 2024-10-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proweb_bot', '0004_alter_grouppost_options_posts_media_posts_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppost',
            options={'verbose_name': 'Пост в Группе', 'verbose_name_plural': 'Посты в Группах'},
        ),
        migrations.AlterModelOptions(
            name='usergrouppost',
            options={'verbose_name': 'Пост в Чате', 'verbose_name_plural': 'Посты в Чатах'},
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, verbose_name='ID сообщения')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('media', models.JSONField(default=list, verbose_name='Список медиа')),
                ('user', models.ManyToManyField(to='proweb_bot.customuser', verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Пост для пользователя',
                'verbose_name_plural': 'Посты для пользователей',
            },
        ),
    ]
