# Generated by Django 5.1.2 on 2024-10-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proweb_bot', '0004_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tg_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID Телеграм'),
        ),
    ]
