# Generated by Django 5.1.2 on 2024-10-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proweb_bot', '0005_customuser_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(default='ru', max_length=10),
        ),
    ]
