# Generated by Django 5.1.2 on 2024-10-14 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proweb_bot', '0007_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Название категории курсов')),
            ],
            options={
                'verbose_name': 'Категория курса',
                'verbose_name_plural': 'Категории курсов',
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proweb_bot.groupscategory', verbose_name='Категория'),
        ),
    ]
