# Generated by Django 5.1.2 on 2024-10-14 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proweb_bot', '0008_groupscategory_groups_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupscategory',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AddField(
            model_name='groups',
            name='language',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Язык группы'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proweb_bot.groupscategory', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='groupscategory',
            name='category_name',
            field=models.CharField(max_length=100, verbose_name='Название курса'),
        ),
    ]
